=== CarlosMedina7e5/Practica_M4/DTD/M4_DTD-Ejercicio3.dtd
<!ELEMENT matricula (ciclo,alumnos)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT alumnos (alumno)+>
<!ELEMENT alumno (nombre,year,asignaturas)>
<!ATTLIST alumno nacionalidad CDATA #FIXED "EspaÃ±ola">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT asignaturas (asignatura)+>
<!ELEMENT asignatura (#PCDATA)>

=== CarlosMedina7e5/Practica_M4/DTD/M4_DTD-Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "M4_DTD-Ejercicio3.dtd">
<matricula>
  <ciclo>DAWe1</ciclo>
  <alumnos>
    <alumno nacionalidad="Española">
      <nombre>Paco</nombre>
      <year>1</year>
      <asignaturas>
        <asignatura>M4</asignatura>
        <asignatura>M1</asignatura>
      </asignaturas>
    </alumno>
    <alumno nacionalidad="Española">
      <nombre>Jorge</nombre>
      <year>1</year>
      <asignaturas>
        <asignatura>M5</asignatura>
        <asignatura>M3</asignatura>
      </asignaturas>
    </alumno>
  </alumnos>  
</matricula>
