=== CarlosMedina7e5/Practica_M4/DTD/M4_DTD-Ejercicio5.dtd
<!ELEMENT Empresa (Empleado+)>
<!ELEMENT Empleado (Apellido+, Nombre, (Email | Telefono), Direccion)>
<!ATTLIST Empleado numEmpleado CDATA #REQUIRED>
<!ELEMENT Apellido (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Direccion EMPTY>
<!ATTLIST Direccion calle CDATA #REQUIRED ciudad CDATA #IMPLIED CP CDATA #IMPLIED>

=== CarlosMedina7e5/Practica_M4/DTD/M4_DTD-Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa SYSTEM "M4_DTD-Ejercicio5.dtd">
<Empresa>
  <Empleado numEmpleado="1234567890">
    <Apellido>Perez</Apellido>
    <Apellido>Perez</Apellido>
    <Nombre>Juan</Nombre>    
    <Email>juanperez@gmail.com</Email>    
    <Direccion calle="Carrer de Pau Claris, 121" ciudad="Barcelona" CP="08009" />      
  </Empleado>
  <Empleado numEmpleado="1234567890">
    <Apellido>Perez</Apellido>
    <Apellido>Perez</Apellido>
    <Nombre>Juan</Nombre>
    <Telefono>juanperez@gmail.com</Telefono> 
    <Direccion calle="Carrer de Pau Claris, 121" ciudad="Barcelona" CP="08009" />      
  </Empleado>
</Empresa>
