=== CarlosMedina7e5/Practica_M4/DTD/MedinaCarlos_recetas.dtd
<!ELEMENT Recetas (Receta+)>
<!ATTLIST Recetas autor CDATA #FIXED "Carlos Medina">
<!ELEMENT Receta (Nombre, Categoria, InfoGeneral?, Ingredientes, Preparacion)>
<!ATTLIST Receta idReceta ID #REQUIRED>
<!ATTLIST Receta fechaAlta CDATA #IMPLIED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Categoria (#PCDATA | SubCategoria)*>
<!ELEMENT SubCategoria (#PCDATA)>
<!ELEMENT InfoGeneral (Foto*, Enlace?, Comensales, Tiempo, Dificultad, Descripcion?)>
<!ELEMENT Foto (#PCDATA)>
<!ELEMENT Enlace (#PCDATA)>
<!ELEMENT Comensales (#PCDATA)>
<!ELEMENT Tiempo (#PCDATA)>
<!ELEMENT Dificultad (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ATTLIST Tiempo unidadTiempo (minutos | horas) "minutos">
<!ELEMENT Ingredientes (Ingrediente, Ingrediente, Ingrediente, Ingrediente+)>
<!ELEMENT Ingrediente (#PCDATA)>
<!ATTLIST Ingrediente unidadDeMedida (gramo | taza | cucharada | cuchara | mililitro) "gramo">
<!ATTLIST Ingrediente cantidad CDATA #IMPLIED>
<!ELEMENT Preparacion (Paso, Paso+)>
<!ELEMENT Paso (#PCDATA)>
<!ATTLIST Paso orden ID #REQUIRED>

=== CarlosMedina7e5/Practica_M4/DTD/MedinaCarlos_recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Recetas SYSTEM "MedinaCarlos_recetas.dtd">
<Recetas autor="Carlos Medina">
    <Receta idReceta="R1" fechaAlta="06/02/2021">
        <Nombre>Croquetas</Nombre>
        <Categoria>
            Comida
            <SubCategoria>Casera</SubCategoria>            
        </Categoria>
        <InfoGeneral>
            <Foto>http://www.unafoto.com</Foto>
            <Enlace>http://www.unenlace.com</Enlace>
            <Comensales>2</Comensales>
            <Tiempo unidadTiempo="minutos">20</Tiempo>
            <Dificultad>Fácil</Dificultad>
            <Descripcion>Croquetas ricas ricas...</Descripcion>
        </InfoGeneral>
        <Ingredientes>
            <Ingrediente cantidad="20" unidadDeMedida="gramo">Jamón</Ingrediente>
            <Ingrediente cantidad="50" unidadDeMedida="gramo">Pan rallado</Ingrediente>
            <Ingrediente cantidad="70" unidadDeMedida="gramo">Sal</Ingrediente>
            <Ingrediente cantidad="50" unidadDeMedida="gramo">Agua</Ingrediente>
        </Ingredientes>
        <Preparacion>
            <Paso orden="P1_1">Abrir el jamón</Paso>
            <Paso orden="P2_1">Picar el jamón</Paso>
        </Preparacion>
    </Receta>
    <Receta idReceta="R2">
        <Nombre>Macarrones</Nombre>
        <Categoria>
            Pasta
            <SubCategoria>Italiano</SubCategoria>            
        </Categoria>
        <InfoGeneral>
            <Foto>http://www.unafoto.com</Foto>
            <Enlace>http://www.unenlace.com</Enlace>
            <Comensales>4</Comensales>
            <Tiempo unidadTiempo="minutos">30</Tiempo>
            <Dificultad>Fácil</Dificultad>
            <Descripcion>Macarrones ricas ricas...</Descripcion>
        </InfoGeneral>
        <Ingredientes>
            <Ingrediente cantidad="20" unidadDeMedida="gramo">Macarrones</Ingrediente>
            <Ingrediente cantidad="50" unidadDeMedida="gramo">Tomate</Ingrediente>
            <Ingrediente cantidad="70" unidadDeMedida="gramo">Sal</Ingrediente>
            <Ingrediente cantidad="50" unidadDeMedida="gramo">Agua</Ingrediente>
        </Ingredientes>
        <Preparacion>
            <Paso orden="P1_2">Abrir los macarrones</Paso>
            <Paso orden="P2_2">Sacar los macarrones</Paso>
        </Preparacion>
    </Receta>
</Recetas>
